# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosnake < Formula
  desc ""
  homepage "https://github.com/streamdp/homebrew-games"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.1/gosnake_Darwin_x86_64.tar.gz"
      sha256 "870e599be2a879cd55c5a21f3cd426c1cf5c24f65445a7a9e5611b223f500afa"

      define_method(:install) do
        bin.install "gosnake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.1/gosnake_Darwin_arm64.tar.gz"
      sha256 "55766515d6e16afce4b1ebedeb93d20381d38c0bce818e188659b2f8fed847c3"

      define_method(:install) do
        bin.install "gosnake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.1/gosnake_Linux_x86_64.tar.gz"
      sha256 "eed5be9769bcd777eaef43306a2127d8f8ab6e7ce94d45c71fbb0f2c779ad47f"
      define_method(:install) do
        bin.install "gosnake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.1/gosnake_Linux_arm64.tar.gz"
      sha256 "edad60b9ddab8df7b7e30d546f7a4bad74d57e279adfd38ab818a78c2c2f3977"
      define_method(:install) do
        bin.install "gosnake"
      end
    end
  end
end
