# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosnake < Formula
  desc ""
  homepage "https://github.com/streamdp/homebrew-games"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.2/gosnake_Darwin_x86_64.tar.gz"
      sha256 "b9889961564cf95aea301ff5be9a458a660c69efc7e9691a6d2b86aaab9f6369"

      define_method(:install) do
        bin.install "gosnake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.2/gosnake_Darwin_arm64.tar.gz"
      sha256 "1d025e3f6c67f81e66c29287ed5e7d0a79b5aec28dc3412e65b84713b7337a44"

      define_method(:install) do
        bin.install "gosnake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.2/gosnake_Linux_x86_64.tar.gz"
      sha256 "a5a8f4c853baf1b5ce7c0a9e135792def6e8fa93eb2d51d71696f75a0aa17487"
      define_method(:install) do
        bin.install "gosnake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamdp/gosnake/releases/download/v1.1.2/gosnake_Linux_arm64.tar.gz"
      sha256 "76406674536e179016cadada10a011cde1ff2effc26af4709ac34f13b6ff016d"
      define_method(:install) do
        bin.install "gosnake"
      end
    end
  end
end
